language: node_js

node_js:
  - "stable"

before_install:
  - npm install -g gulp
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-redirect --white-list travis-ci
  - gulp coveralls
